export const FETCH_SECTION = 'FETCH_SECTION';
export const FETCH_SECTION_SUCCESS = 'FETCH_SECTION_SUCCESS';
export const FETCH_SECTION_FAILURE = 'FETCH_SECTION_FAILURE';
export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';

export const FETCH_START_PAGE = 'FETCH_START_PAGE';
export const FETCH_START_PAGE_SUCCESS = 'FETCH_START_PAGE_SUCCESS';
export const FETCH_START_PAGE_FAILURE = 'FETCH_START_PAGE_FAILURE';
export const FETCH_THERAPY_PAGE = 'FETCH_THERAPY_PAGE';
export const FETCH_THERAPY_PAGE_SUCCESS = 'FETCH_THERAPY_PAGE_SUCCESS';
export const FETCH_THERAPY_PAGE_FAILURE = 'FETCH_THERAPY_PAGE_FAILURE';
export const FETCH_FERTILITY_PAGE = 'FETCH_FERTILITY_PAGE';
export const FETCH_FERTILITY_PAGE_SUCCESS = 'FETCH_FERTILITY_PAGE_SUCCESS';
export const FETCH_FERTILITY_PAGE_FAILURE = 'FETCH_FERTILITY_PAGE_FAILURE';
export const FETCH_ABOUT_PAGE = 'FETCH_ABOUT_PAGE';
export const FETCH_ABOUT_PAGE_SUCCESS = 'FETCH_ABOUT_PAGE_SUCCESS';
export const FETCH_ABOUT_PAGE_FAILURE = 'FETCH_ABOUT_PAGE_FAILURE';

export const TRANSLATE_START_PAGE = 'TRANSLATE_START_PAGE';
export const TRANSLATE_START_PAGE_SUCCESS = 'TRANSLATE_START_PAGE_SUCCESS';
export const TRANSLATE_START_PAGE_FAILURE = 'TRANSLATE_START_PAGE_FAILURE';
export const TRANSLATE_THERAPY_PAGE = 'TRANSLATE_THERAPY_PAGE';
export const TRANSLATE_THERAPY_PAGE_SUCCESS = 'TRANSLATE_THERAPY_PAGE_SUCCESS';
export const TRANSLATE_THERAPY_PAGE_FAILURE = 'TRANSLATE_THERAPY_PAGE_FAILURE';
export const TRANSLATE_FERTILITY_PAGE = 'TRANSLATE_FERTILITY_PAGE';
export const TRANSLATE_FERTILITY_PAGE_SUCCESS = 'TRANSLATE_FERTILITY_PAGE_SUCCESS';
export const TRANSLATE_FERTILITY_PAGE_FAILURE = 'TRANSLATE_FERTILITY_PAGE_FAILURE';
export const TRANSLATE_ABOUT_PAGE = 'TRANSLATE_ABOUT_PAGE';
export const TRANSLATE_ABOUT_PAGE_SUCCESS = 'TRANSLATE_ABOUT_PAGE_SUCCESS';
export const TRANSLATE_ABOUT_PAGE_FAILURE = 'TRANSLATE_ABOUT_PAGE_FAILURE';

export const TRANSLATE_SECTION = 'TRANSLATE_SECTION';
export const TRANSLATE_SECTION_SUCCESS = 'TRANSLATE_SECTION_SUCCESS';
export const TRANSLATE_SECTION_FAILURE = 'TRANSLATE_SECTION_FAILURE';
